Update build-with-docker.yml

diff --git a/.github/workflows/build-with-docker.yml b/.github/workflows/build-with-docker.yml
--- a/.github/workflows/build-with-docker.yml
+++ b/.github/workflows/build-with-docker.yml
@@ -204,16 +204,16 @@ jobs:
               sudo rm -rf build/cache/toolchain/*
               sudo mkdir -p build/cache/toolchain build/cache/rootfs || true
               ! sudo mountpoint -q cache/toolchain && sudo mount nas:/tank/armbian/toolchain.armbian.com build/cache/toolchain -o rsize=32768,wsize=32768,timeo=5,retrans=2,actimeo=60,retry=3 || true
-              ! sudo mountpoint -q cache/rootfs && sudo mount nas:/tank/armbian/cache.armbian.com/rootfs build/cache/rootfs -o rsize=32768,wsize=32768,timeo=5,retrans=2,actimeo=60,retry=3 || true
+#              ! sudo mountpoint -q cache/rootfs && sudo mount nas:/tank/armbian/cache.armbian.com/rootfs build/cache/rootfs -o rsize=32768,wsize=32768,timeo=5,retrans=2,actimeo=60,retry=3 || true
           fi
           
-          if [[ $(curl -s http://ifconfig.me) == "188.227.12.36" || $(curl -s http://ifconfig.me) == "206.82.251.151" ]]; then
-              sudo rm -rf build/cache/sources
-              sudo mkdir -p build/cache/toolchain build/cache/rootfs || true
-              # sudo mount -a
-              ! sudo mountpoint -q build/cache/toolchain && sudo mount --bind /mnt/armbian/cache/toolchain/ build/cache/toolchain -o rsize=32768,wsize=32768,timeo=5,retrans=2,actimeo=60,retry=3 || true
-              ! sudo mountpoint -q build/cache/rootfs && sudo mount --bind /mnt/armbian/cache/rootfs/ build/cache/rootfs/ -o rsize=32768,wsize=32768,timeo=5,retrans=2,actimeo=60,retry=3 || true
-          fi
+#          if [[ $(curl -s http://ifconfig.me) == "188.227.12.36" || $(curl -s http://ifconfig.me) == "206.82.251.151" ]]; then
+#              sudo rm -rf build/cache/sources
+#              sudo mkdir -p build/cache/toolchain build/cache/rootfs || true
+#              # sudo mount -a
+#              ! sudo mountpoint -q build/cache/toolchain && sudo mount --bind /mnt/armbian/cache/toolchain/ build/cache/toolchain -o rsize=32768,wsize=32768,timeo=5,retrans=2,actimeo=60,retry=3 || true
+#              ! sudo mountpoint -q build/cache/rootfs && sudo mount --bind /mnt/armbian/cache/rootfs/ build/cache/rootfs/ -o rsize=32768,wsize=32768,timeo=5,retrans=2,actimeo=60,retry=3 || true
+#          fi
           
           var="${{ inputs.variant }}"
           RC="no"
