Update build-kernel.yml

diff --git a/.github/workflows/build-kernel.yml b/.github/workflows/build-kernel.yml
--- a/.github/workflows/build-kernel.yml
+++ b/.github/workflows/build-kernel.yml
@@ -201,8 +201,10 @@ jobs:
               echo "FILE_HASH=$(ls -1 cache/hash-beta/*.githash | head -1)"  >> $GITHUB_ENV
               echo "FILE_NAME=${BRANCH}-${FAMILY}" >> $GITHUB_ENV
               echo "UPLOAD=true" >> $GITHUB_ENV
+              # Cleanup
+              sudo find output/debs-beta/. -type f -not \( -name 'linux*' -or -name 'armbian*' \) -print0 | sudo xargs -0 -I {} rm {}
               # copy edge brach to stable repo
-              # cp output/debs-beta/linux-{dtb,image,source,headers}-edge-* output/debs/ || true
+              sudo cp output/debs-beta/linux-{dtb,image,source,headers}-edge-* output/debs/ || true
           fi
 
       - name: Upload hash
