Update build-u-boot-with-docker.yml

diff --git a/.github/workflows/build-u-boot-with-docker.yml b/.github/workflows/build-u-boot-with-docker.yml
--- a/.github/workflows/build-u-boot-with-docker.yml
+++ b/.github/workflows/build-u-boot-with-docker.yml
@@ -134,7 +134,18 @@ jobs:
           [[ -d build/.git ]] && sudo chown -R $USER:$USER build/.git || true
           [[ -d build/output/images ]] && sudo rm -rf build/output/images/* || true
          
-       
+      - name: Mount upload folders
+        run: |
+        
+          # mount deploy target
+          sudo apt-get -y -qq install sshfs
+          sudo mkdir -p /root/.ssh/
+          sudo cp ~/.ssh/known_hosts /root/.ssh/
+          sudo mkdir -p build/output/debs || true
+          sudo mkdir -p build/output/debs-beta || true
+          sudo sshfs upload@users.armbian.com:/debs build/output/debs -o IdentityFile=~/.ssh/id_rsa -o reconnect,nonempty -o allow_other
+          sudo sshfs upload@users.armbian.com:/debs-beta build/output/debs-beta -o IdentityFile=~/.ssh/id_rsa -o reconnect,nonempty -o allow_other
+
       - name: Build
         run: |
 
@@ -185,11 +196,19 @@ jobs:
           path: build/output/debs-beta/*u-boot*
           if-no-files-found: ignore
 
-      - name: Deploy to server
-        if: ${{ success() }}
-        run: |
+#      - name: Deploy to server
+#        if: ${{ success() }}
+#        run: |
+#
+#          while fuser /var/{lib/{dpkg,apt/lists},cache/apt/archives}/lock >/dev/null 2>&1; do sleep 1; done;
+#          sudo apt-get -y -qq install lftp
+#          sudo chown -R $USER:$USER build/output/debs-beta/
+#          lftp -u upload, -e "set net:timeout 10;set net:max-retries 16;mirror --Remove-source-files -R --no-empty-dirs --parallel=8 --no-perms $(pwd)/build/output/debs-beta/ debs-beta/ ;bye" sftp://users.armbian.com
 
-          while fuser /var/{lib/{dpkg,apt/lists},cache/apt/archives}/lock >/dev/null 2>&1; do sleep 1; done;
-          sudo apt-get -y -qq install lftp
-          sudo chown -R $USER:$USER build/output/debs-beta/
-          lftp -u upload, -e "set net:timeout 10;set net:max-retries 16;mirror --Remove-source-files -R --no-empty-dirs --parallel=8 --no-perms $(pwd)/build/output/debs-beta/ debs-beta/ ;bye" sftp://users.armbian.com
+      - name: Unmount folders
+        
+        run: |
+         
+            sudo mountpoint -q build/output/debs && sudo fusermount -u build/output/debs || true
+            sudo mountpoint -q build/output/debs-beta && sudo fusermount -u build/output/debs-beta || true
+            sudo mountpoint -q build/cache/toolchain && sudo fusermount -u build/cache/toolchain || true
