Update smoke-tests.yml

diff --git a/.github/workflows/smoke-tests.yml b/.github/workflows/smoke-tests.yml
--- a/.github/workflows/smoke-tests.yml
+++ b/.github/workflows/smoke-tests.yml
@@ -106,7 +106,7 @@ jobs:
         if: ${{ github.repository_owner == 'Armbian' && env.PROCEED == 'true' }}
         run: |
 
-          ssh -i ~/.ssh/duts -o StrictHostKeyChecking=no root@${{ env.DUT_IP }} "dpkg --configure -a; apt-get -y install neofetch datamash" || true
+          ssh -i ~/.ssh/duts -o StrictHostKeyChecking=no root@${{ env.DUT_IP }} "dpkg --configure -a; apt-get -y install neofetch datamash p7zip" || true
           ssh -i ~/.ssh/duts -o StrictHostKeyChecking=no root@${{ env.DUT_IP }} "timeout 60 neofetch" || true
 
       - name: To nightly
@@ -150,6 +150,15 @@ jobs:
             echo "The server is busy running a test"
             sleep 2
           done
+
+      - name: 7Zip
+        if: ${{ github.repository_owner == 'Armbian' && env.PROCEED == 'true' }}
+        run: |
+
+            SEVENZIP=$(timeout 1000 ssh -i ~/.ssh/duts -o StrictHostKeyChecking=no root@${{ env.DUT_IP }} "7z b | grep 'Tot:' | awk '{print $NF}'")
+            if [[ -n "${SEVENZIP}" ]] ; then
+              echo "SEVENZIP=${SEVENZIP}" >> $GITHUB_ENV
+            fi
 
       - name: Reboot
         if: ${{ github.repository_owner == 'Armbian' && env.PROCEED == 'true' }}
@@ -223,15 +232,15 @@ jobs:
       - name: Calculate
         run: |
 
-          echo "|IP|DUT|U-boot|Kernel|Iperf|Online|Reboot|" > status.md
-          echo "|:--|:--|:--|--:|--:|:--:|:--:|" >> status.md 
+          echo "|IP|DUT|U-boot|Kernel|Iperf|7Z bench|Online|Reboot|" > status.md
+          echo "|:--|:--|:--|--:|--:|--:|:--:|:--:|" >> status.md 
           cat status/*.md >> status.md 
           cat status.md >> $GITHUB_STEP_SUMMARY
           #
           ls -1 status | wc -l > status/total
           grep false status/* | cut -d":" -f2 | cut -d"," -f1-2 > status/failed
-          echo "scale=2 ; (100*($(cat status/total.txt)-$(cat status/failed.txt | wc -l))/$(cat status/total.txt))" | bc > status/success
-          rm -f status/*.txt
+          echo "scale=2 ; (100*($(cat status/total)-$(cat status/failed | wc -l))/$(cat status/total))" | bc > status/success
+          rm -f status/*.*
 
       - name: Upload status
         if: ${{ github.repository_owner == 'Armbian' }}
